.\"
.\" sc_ipiddump.1
.\"
.\" Author: Matthew Luckie <mjl@luckie.org.nz>
.\"
.\" Copyright (c) 2013 The Regents of the University of California
.\"                    All rights reserved
.\"
.\" $Id: sc_ipiddump.1,v 1.2 2015/08/27 18:28:35 mjl Exp $
.\"
.Dd August 19, 2013
.Dt SC_IPIDDUMP 1
.Os
.Sh NAME
.Nm sc_ipiddump
.Nd utility to dump IP-ID values embedded in ping and dealias objects in warts files.
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl U Ar userid
.Op Ar
.Ek
.\""""""""""""
.Sh DESCRIPTION
The
.Nm
utility dumps the IP-ID values embedded in IPv4 and IPv6 responses to
ping and dealias objects.  The output contains the transit and receive
timestamps, the source address used by scamper when probing, the
interface address which replied, and the IPID value (in hexadecimal).
The objects are sorted by transit time.
The supported options to
.Nm
are as follows:
.Bl -tag -width Ds
.It Fl U Ar userid
restricts the selection of warts objects to those with the given userid(s).
.El
.\""""""""""""
.Sh EXAMPLES
Given an input file foo.warts, the following command dumps IP-ID values found
in objects with userid values 3 and 4:
.Pp
.Dl sc_ipiddump -U 3,4 foo.warts
.Pp
.\""""""""""""
.Sh SEE ALSO
.Xr scamper 1 ,
.Xr sc_wartsdump 1 ,
.Xr sc_warts2text 1 ,
.Xr sc_warts2json 1
.Sh AUTHORS
.Nm
was written by Matthew Luckie <mjl@luckie.org.nz>.
