// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/NEU-SNS/ReverseTraceroute/datamodel/recspoof.proto

package datamodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TSType int32

const (
	TSType_TSOnly    TSType = 0
	TSType_TSAndAddr TSType = 1
	TSType_TSPreSpec TSType = 3
)

var TSType_name = map[int32]string{
	0: "TSOnly",
	1: "TSAndAddr",
	3: "TSPreSpec",
}

var TSType_value = map[string]int32{
	"TSOnly":    0,
	"TSAndAddr": 1,
	"TSPreSpec": 3,
}

func (x TSType) String() string {
	return proto.EnumName(TSType_name, int32(x))
}

func (TSType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{0}
}

type RecSpoof struct {
	Spoofs               []*Spoof `protobuf:"bytes,1,rep,name=spoofs,proto3" json:"spoofs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecSpoof) Reset()         { *m = RecSpoof{} }
func (m *RecSpoof) String() string { return proto.CompactTextString(m) }
func (*RecSpoof) ProtoMessage()    {}
func (*RecSpoof) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{0}
}

func (m *RecSpoof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecSpoof.Unmarshal(m, b)
}
func (m *RecSpoof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecSpoof.Marshal(b, m, deterministic)
}
func (m *RecSpoof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecSpoof.Merge(m, src)
}
func (m *RecSpoof) XXX_Size() int {
	return xxx_messageInfo_RecSpoof.Size(m)
}
func (m *RecSpoof) XXX_DiscardUnknown() {
	xxx_messageInfo_RecSpoof.DiscardUnknown(m)
}

var xxx_messageInfo_RecSpoof proto.InternalMessageInfo

func (m *RecSpoof) GetSpoofs() []*Spoof {
	if m != nil {
		return m.Spoofs
	}
	return nil
}

type Spoof struct {
	Ip                   uint32   `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Sip                  uint32   `protobuf:"varint,3,opt,name=sip,proto3" json:"sip,omitempty"`
	Dst                  uint32   `protobuf:"varint,4,opt,name=dst,proto3" json:"dst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spoof) Reset()         { *m = Spoof{} }
func (m *Spoof) String() string { return proto.CompactTextString(m) }
func (*Spoof) ProtoMessage()    {}
func (*Spoof) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{1}
}

func (m *Spoof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spoof.Unmarshal(m, b)
}
func (m *Spoof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spoof.Marshal(b, m, deterministic)
}
func (m *Spoof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spoof.Merge(m, src)
}
func (m *Spoof) XXX_Size() int {
	return xxx_messageInfo_Spoof.Size(m)
}
func (m *Spoof) XXX_DiscardUnknown() {
	xxx_messageInfo_Spoof.DiscardUnknown(m)
}

var xxx_messageInfo_Spoof proto.InternalMessageInfo

func (m *Spoof) GetIp() uint32 {
	if m != nil {
		return m.Ip
	}
	return 0
}

func (m *Spoof) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Spoof) GetSip() uint32 {
	if m != nil {
		return m.Sip
	}
	return 0
}

func (m *Spoof) GetDst() uint32 {
	if m != nil {
		return m.Dst
	}
	return 0
}

type SpoofedProbes struct {
	Probes               []*Probe `protobuf:"bytes,1,rep,name=probes,proto3" json:"probes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpoofedProbes) Reset()         { *m = SpoofedProbes{} }
func (m *SpoofedProbes) String() string { return proto.CompactTextString(m) }
func (*SpoofedProbes) ProtoMessage()    {}
func (*SpoofedProbes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{2}
}

func (m *SpoofedProbes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpoofedProbes.Unmarshal(m, b)
}
func (m *SpoofedProbes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpoofedProbes.Marshal(b, m, deterministic)
}
func (m *SpoofedProbes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpoofedProbes.Merge(m, src)
}
func (m *SpoofedProbes) XXX_Size() int {
	return xxx_messageInfo_SpoofedProbes.Size(m)
}
func (m *SpoofedProbes) XXX_DiscardUnknown() {
	xxx_messageInfo_SpoofedProbes.DiscardUnknown(m)
}

var xxx_messageInfo_SpoofedProbes proto.InternalMessageInfo

func (m *SpoofedProbes) GetProbes() []*Probe {
	if m != nil {
		return m.Probes
	}
	return nil
}

type SpoofedProbesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpoofedProbesResponse) Reset()         { *m = SpoofedProbesResponse{} }
func (m *SpoofedProbesResponse) String() string { return proto.CompactTextString(m) }
func (*SpoofedProbesResponse) ProtoMessage()    {}
func (*SpoofedProbesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{3}
}

func (m *SpoofedProbesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpoofedProbesResponse.Unmarshal(m, b)
}
func (m *SpoofedProbesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpoofedProbesResponse.Marshal(b, m, deterministic)
}
func (m *SpoofedProbesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpoofedProbesResponse.Merge(m, src)
}
func (m *SpoofedProbesResponse) XXX_Size() int {
	return xxx_messageInfo_SpoofedProbesResponse.Size(m)
}
func (m *SpoofedProbesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpoofedProbesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpoofedProbesResponse proto.InternalMessageInfo

type Probe struct {
	SpooferIp            uint32       `protobuf:"varint,1,opt,name=spoofer_ip,json=spooferIp,proto3" json:"spoofer_ip,omitempty"`
	ProbeId              uint32       `protobuf:"varint,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	Src                  uint32       `protobuf:"varint,4,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  uint32       `protobuf:"varint,5,opt,name=dst,proto3" json:"dst,omitempty"`
	Id                   uint32       `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	SeqNum               uint32       `protobuf:"varint,7,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	RR                   *RecordRoute `protobuf:"bytes,8,opt,name=r_r,json=rR,proto3" json:"r_r,omitempty"`
	Ts                   *TimeStamp   `protobuf:"bytes,9,opt,name=ts,proto3" json:"ts,omitempty"`
	SenderIp             uint32       `protobuf:"varint,10,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Probe) Reset()         { *m = Probe{} }
func (m *Probe) String() string { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()    {}
func (*Probe) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{4}
}

func (m *Probe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Probe.Unmarshal(m, b)
}
func (m *Probe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Probe.Marshal(b, m, deterministic)
}
func (m *Probe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Probe.Merge(m, src)
}
func (m *Probe) XXX_Size() int {
	return xxx_messageInfo_Probe.Size(m)
}
func (m *Probe) XXX_DiscardUnknown() {
	xxx_messageInfo_Probe.DiscardUnknown(m)
}

var xxx_messageInfo_Probe proto.InternalMessageInfo

func (m *Probe) GetSpooferIp() uint32 {
	if m != nil {
		return m.SpooferIp
	}
	return 0
}

func (m *Probe) GetProbeId() uint32 {
	if m != nil {
		return m.ProbeId
	}
	return 0
}

func (m *Probe) GetSrc() uint32 {
	if m != nil {
		return m.Src
	}
	return 0
}

func (m *Probe) GetDst() uint32 {
	if m != nil {
		return m.Dst
	}
	return 0
}

func (m *Probe) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Probe) GetSeqNum() uint32 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *Probe) GetRR() *RecordRoute {
	if m != nil {
		return m.RR
	}
	return nil
}

func (m *Probe) GetTs() *TimeStamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Probe) GetSenderIp() uint32 {
	if m != nil {
		return m.SenderIp
	}
	return 0
}

type RecordRoute struct {
	Hops                 []uint32 `protobuf:"varint,1,rep,packed,name=hops,proto3" json:"hops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordRoute) Reset()         { *m = RecordRoute{} }
func (m *RecordRoute) String() string { return proto.CompactTextString(m) }
func (*RecordRoute) ProtoMessage()    {}
func (*RecordRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{5}
}

func (m *RecordRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRoute.Unmarshal(m, b)
}
func (m *RecordRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRoute.Marshal(b, m, deterministic)
}
func (m *RecordRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRoute.Merge(m, src)
}
func (m *RecordRoute) XXX_Size() int {
	return xxx_messageInfo_RecordRoute.Size(m)
}
func (m *RecordRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRoute.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRoute proto.InternalMessageInfo

func (m *RecordRoute) GetHops() []uint32 {
	if m != nil {
		return m.Hops
	}
	return nil
}

type TimeStamp struct {
	Type                 TSType   `protobuf:"varint,1,opt,name=type,proto3,enum=datamodel.TSType" json:"type,omitempty"`
	Stamps               []*Stamp `protobuf:"bytes,2,rep,name=stamps,proto3" json:"stamps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeStamp) Reset()         { *m = TimeStamp{} }
func (m *TimeStamp) String() string { return proto.CompactTextString(m) }
func (*TimeStamp) ProtoMessage()    {}
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{6}
}

func (m *TimeStamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeStamp.Unmarshal(m, b)
}
func (m *TimeStamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeStamp.Marshal(b, m, deterministic)
}
func (m *TimeStamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeStamp.Merge(m, src)
}
func (m *TimeStamp) XXX_Size() int {
	return xxx_messageInfo_TimeStamp.Size(m)
}
func (m *TimeStamp) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeStamp.DiscardUnknown(m)
}

var xxx_messageInfo_TimeStamp proto.InternalMessageInfo

func (m *TimeStamp) GetType() TSType {
	if m != nil {
		return m.Type
	}
	return TSType_TSOnly
}

func (m *TimeStamp) GetStamps() []*Stamp {
	if m != nil {
		return m.Stamps
	}
	return nil
}

type Stamp struct {
	Time                 uint32   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Ip                   uint32   `protobuf:"varint,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stamp) Reset()         { *m = Stamp{} }
func (m *Stamp) String() string { return proto.CompactTextString(m) }
func (*Stamp) ProtoMessage()    {}
func (*Stamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{7}
}

func (m *Stamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stamp.Unmarshal(m, b)
}
func (m *Stamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stamp.Marshal(b, m, deterministic)
}
func (m *Stamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stamp.Merge(m, src)
}
func (m *Stamp) XXX_Size() int {
	return xxx_messageInfo_Stamp.Size(m)
}
func (m *Stamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Stamp.DiscardUnknown(m)
}

var xxx_messageInfo_Stamp proto.InternalMessageInfo

func (m *Stamp) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Stamp) GetIp() uint32 {
	if m != nil {
		return m.Ip
	}
	return 0
}

type NotifyRecSpoofResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRecSpoofResponse) Reset()         { *m = NotifyRecSpoofResponse{} }
func (m *NotifyRecSpoofResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyRecSpoofResponse) ProtoMessage()    {}
func (*NotifyRecSpoofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{8}
}

func (m *NotifyRecSpoofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRecSpoofResponse.Unmarshal(m, b)
}
func (m *NotifyRecSpoofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRecSpoofResponse.Marshal(b, m, deterministic)
}
func (m *NotifyRecSpoofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRecSpoofResponse.Merge(m, src)
}
func (m *NotifyRecSpoofResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyRecSpoofResponse.Size(m)
}
func (m *NotifyRecSpoofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRecSpoofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRecSpoofResponse proto.InternalMessageInfo

func (m *NotifyRecSpoofResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ReceiveSpoofedProbesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveSpoofedProbesResponse) Reset()         { *m = ReceiveSpoofedProbesResponse{} }
func (m *ReceiveSpoofedProbesResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveSpoofedProbesResponse) ProtoMessage()    {}
func (*ReceiveSpoofedProbesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a89fe260642ce26, []int{9}
}

func (m *ReceiveSpoofedProbesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveSpoofedProbesResponse.Unmarshal(m, b)
}
func (m *ReceiveSpoofedProbesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveSpoofedProbesResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveSpoofedProbesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveSpoofedProbesResponse.Merge(m, src)
}
func (m *ReceiveSpoofedProbesResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveSpoofedProbesResponse.Size(m)
}
func (m *ReceiveSpoofedProbesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveSpoofedProbesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveSpoofedProbesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("datamodel.TSType", TSType_name, TSType_value)
	proto.RegisterType((*RecSpoof)(nil), "datamodel.RecSpoof")
	proto.RegisterType((*Spoof)(nil), "datamodel.Spoof")
	proto.RegisterType((*SpoofedProbes)(nil), "datamodel.SpoofedProbes")
	proto.RegisterType((*SpoofedProbesResponse)(nil), "datamodel.SpoofedProbesResponse")
	proto.RegisterType((*Probe)(nil), "datamodel.Probe")
	proto.RegisterType((*RecordRoute)(nil), "datamodel.RecordRoute")
	proto.RegisterType((*TimeStamp)(nil), "datamodel.TimeStamp")
	proto.RegisterType((*Stamp)(nil), "datamodel.Stamp")
	proto.RegisterType((*NotifyRecSpoofResponse)(nil), "datamodel.NotifyRecSpoofResponse")
	proto.RegisterType((*ReceiveSpoofedProbesResponse)(nil), "datamodel.ReceiveSpoofedProbesResponse")
}

func init() {
	proto.RegisterFile("github.com/NEU-SNS/ReverseTraceroute/datamodel/recspoof.proto", fileDescriptor_2a89fe260642ce26)
}

var fileDescriptor_2a89fe260642ce26 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6b, 0x1b, 0x31,
	0x10, 0xed, 0xae, 0x3f, 0x77, 0x8c, 0xc3, 0x56, 0xa4, 0xce, 0x96, 0x7e, 0x60, 0x44, 0x43, 0x4d,
	0x4b, 0x6d, 0x70, 0x7b, 0xe9, 0xa1, 0x87, 0x04, 0x7a, 0x30, 0x05, 0x37, 0x68, 0xdd, 0x4b, 0x29,
	0x18, 0x7b, 0x35, 0x69, 0x16, 0xb2, 0x96, 0x22, 0xc9, 0x01, 0xff, 0xf5, 0x9e, 0xca, 0x8e, 0x76,
	0xb7, 0x2e, 0xc9, 0x6d, 0xe6, 0xbd, 0xa7, 0xd1, 0x1b, 0xcd, 0x08, 0xbe, 0xfc, 0xce, 0xdd, 0xcd,
	0x7e, 0x3b, 0xcd, 0x54, 0x31, 0x5b, 0x7e, 0xfd, 0xf1, 0x21, 0x5d, 0xa6, 0x33, 0x81, 0xf7, 0x68,
	0x2c, 0xae, 0xcc, 0x26, 0x43, 0xa3, 0xf6, 0x0e, 0x67, 0x72, 0xe3, 0x36, 0x85, 0x92, 0x78, 0x3b,
	0x33, 0x98, 0x59, 0xad, 0xd4, 0xf5, 0x54, 0x1b, 0xe5, 0x14, 0x8b, 0x1a, 0x86, 0x7f, 0x82, 0xbe,
	0xc0, 0x2c, 0x2d, 0x49, 0x36, 0x81, 0x2e, 0xa9, 0x6c, 0x12, 0x8c, 0x5b, 0x93, 0xc1, 0x3c, 0x9e,
	0x36, 0xba, 0x29, 0x29, 0x44, 0xc5, 0xf3, 0x6f, 0xd0, 0xf1, 0x47, 0x4e, 0x20, 0xcc, 0x75, 0x12,
	0x8c, 0x83, 0xc9, 0x50, 0x84, 0xb9, 0xa6, 0x5c, 0x26, 0x61, 0x95, 0x4b, 0x16, 0x43, 0xcb, 0xe6,
	0x3a, 0x69, 0x11, 0x50, 0x86, 0x25, 0x22, 0xad, 0x4b, 0xda, 0x1e, 0x91, 0xd6, 0xf1, 0xcf, 0x30,
	0xa4, 0x62, 0x28, 0xaf, 0x8c, 0xda, 0xa2, 0x2d, 0x7d, 0x68, 0x8a, 0x1e, 0xf1, 0x41, 0x12, 0x51,
	0xf1, 0xfc, 0x0c, 0x9e, 0xfd, 0x77, 0x54, 0xa0, 0xd5, 0x6a, 0x67, 0x91, 0xff, 0x09, 0xa0, 0x43,
	0x10, 0x7b, 0x05, 0x40, 0xa6, 0xd1, 0xac, 0x1b, 0xa7, 0x51, 0x85, 0x2c, 0x34, 0x7b, 0x0e, 0x7d,
	0xaa, 0xb5, 0x6e, 0x6c, 0xf7, 0x28, 0x5f, 0x78, 0xef, 0x26, 0xab, 0x9d, 0x5a, 0x93, 0xd5, 0xde,
	0x3b, 0x8d, 0xf7, 0xaa, 0xdf, 0x6e, 0xd3, 0xef, 0x19, 0xf4, 0x2c, 0xde, 0xad, 0x77, 0xfb, 0x22,
	0xe9, 0x11, 0xd8, 0xb5, 0x78, 0xb7, 0xdc, 0x17, 0xec, 0x2d, 0xb4, 0xcc, 0xda, 0x24, 0xfd, 0x71,
	0x30, 0x19, 0xcc, 0x47, 0x47, 0x0d, 0x09, 0xcc, 0x94, 0x91, 0xa2, 0x1c, 0x98, 0x08, 0x8d, 0x60,
	0x6f, 0x20, 0x74, 0x36, 0x89, 0x48, 0x77, 0x7a, 0xa4, 0x5b, 0xe5, 0x05, 0xa6, 0x6e, 0x53, 0x68,
	0x11, 0x3a, 0xcb, 0x5e, 0x40, 0x64, 0x71, 0x27, 0x7d, 0x53, 0x40, 0x37, 0xf5, 0x3d, 0xb0, 0xd0,
	0xfc, 0x1c, 0x06, 0x47, 0x55, 0xd9, 0x08, 0xda, 0x37, 0x4a, 0xfb, 0xc7, 0x1c, 0x5e, 0x86, 0x71,
	0x20, 0x28, 0xe7, 0xbf, 0x20, 0x6a, 0x8a, 0xb2, 0x73, 0x68, 0xbb, 0x83, 0x46, 0x7a, 0xa0, 0x93,
	0xf9, 0xd3, 0xe3, 0x8b, 0xd3, 0xd5, 0x41, 0xa3, 0x20, 0x9a, 0x56, 0xa4, 0xd4, 0xdb, 0x24, 0x7c,
	0xb8, 0x22, 0xe4, 0xae, 0xe2, 0xf9, 0x7b, 0xe8, 0xf8, 0xca, 0x0c, 0xda, 0x2e, 0x2f, 0xb0, 0x7a,
	0x7a, 0x8a, 0xab, 0xb5, 0xa9, 0xd7, 0x44, 0xf3, 0x29, 0x8c, 0x96, 0xca, 0xe5, 0xd7, 0x87, 0x7a,
	0x17, 0xeb, 0x41, 0xb2, 0x53, 0xe8, 0xa0, 0x31, 0xca, 0xd0, 0xf1, 0x48, 0xf8, 0x84, 0xbf, 0x86,
	0x97, 0x02, 0x33, 0xcc, 0xef, 0xf1, 0xd1, 0xf1, 0xbf, 0x9b, 0x43, 0xd7, 0xdb, 0x66, 0x50, 0x46,
	0xdf, 0x77, 0xb7, 0x87, 0xf8, 0x09, 0x1b, 0x42, 0xb4, 0x4a, 0x2f, 0x76, 0xf2, 0x42, 0x4a, 0x13,
	0x07, 0x3e, 0xbd, 0x32, 0x98, 0x6a, 0xcc, 0xe2, 0xd6, 0xe5, 0xe0, 0xe7, 0xbf, 0x6f, 0xb1, 0xed,
	0xd2, 0x47, 0xf9, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x69, 0x82, 0x6e, 0x69, 0x03, 0x00,
	0x00,
}
