// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: recspoof.proto

package datamodel

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TSType int32

const (
	TSType_TSOnly    TSType = 0
	TSType_TSAndAddr TSType = 1
	TSType_TSPreSpec TSType = 3
)

// Enum value maps for TSType.
var (
	TSType_name = map[int32]string{
		0: "TSOnly",
		1: "TSAndAddr",
		3: "TSPreSpec",
	}
	TSType_value = map[string]int32{
		"TSOnly":    0,
		"TSAndAddr": 1,
		"TSPreSpec": 3,
	}
)

func (x TSType) Enum() *TSType {
	p := new(TSType)
	*p = x
	return p
}

func (x TSType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TSType) Descriptor() protoreflect.EnumDescriptor {
	return file_recspoof_proto_enumTypes[0].Descriptor()
}

func (TSType) Type() protoreflect.EnumType {
	return &file_recspoof_proto_enumTypes[0]
}

func (x TSType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TSType.Descriptor instead.
func (TSType) EnumDescriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{0}
}

type RecSpoof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spoofs []*Spoof `protobuf:"bytes,1,rep,name=spoofs,proto3" json:"spoofs,omitempty"`
}

func (x *RecSpoof) Reset() {
	*x = RecSpoof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecSpoof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecSpoof) ProtoMessage() {}

func (x *RecSpoof) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecSpoof.ProtoReflect.Descriptor instead.
func (*RecSpoof) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{0}
}

func (x *RecSpoof) GetSpoofs() []*Spoof {
	if x != nil {
		return x.Spoofs
	}
	return nil
}

type Spoof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip  uint32 `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Id  uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Sip uint32 `protobuf:"varint,3,opt,name=sip,proto3" json:"sip,omitempty"`
	Dst uint32 `protobuf:"varint,4,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *Spoof) Reset() {
	*x = Spoof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spoof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spoof) ProtoMessage() {}

func (x *Spoof) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spoof.ProtoReflect.Descriptor instead.
func (*Spoof) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{1}
}

func (x *Spoof) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

func (x *Spoof) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Spoof) GetSip() uint32 {
	if x != nil {
		return x.Sip
	}
	return 0
}

func (x *Spoof) GetDst() uint32 {
	if x != nil {
		return x.Dst
	}
	return 0
}

type SpoofedProbes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probes []*Probe `protobuf:"bytes,1,rep,name=probes,proto3" json:"probes,omitempty"`
}

func (x *SpoofedProbes) Reset() {
	*x = SpoofedProbes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpoofedProbes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpoofedProbes) ProtoMessage() {}

func (x *SpoofedProbes) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpoofedProbes.ProtoReflect.Descriptor instead.
func (*SpoofedProbes) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{2}
}

func (x *SpoofedProbes) GetProbes() []*Probe {
	if x != nil {
		return x.Probes
	}
	return nil
}

type SpoofedProbesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpoofedProbesResponse) Reset() {
	*x = SpoofedProbesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpoofedProbesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpoofedProbesResponse) ProtoMessage() {}

func (x *SpoofedProbesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpoofedProbesResponse.ProtoReflect.Descriptor instead.
func (*SpoofedProbesResponse) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{3}
}

type Probe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpooferIp         uint32       `protobuf:"varint,1,opt,name=spoofer_ip,json=spooferIp,proto3" json:"spoofer_ip,omitempty"`
	ProbeId           uint32       `protobuf:"varint,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	Src               uint32       `protobuf:"varint,4,opt,name=src,proto3" json:"src,omitempty"`
	Dst               uint32       `protobuf:"varint,5,opt,name=dst,proto3" json:"dst,omitempty"`
	Id                uint32       `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	SeqNum            uint32       `protobuf:"varint,7,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	RR                *RecordRoute `protobuf:"bytes,8,opt,name=r_r,json=rR,proto3" json:"r_r,omitempty"`
	Ts                *TimeStamp   `protobuf:"bytes,9,opt,name=ts,proto3" json:"ts,omitempty"`
	SenderIp          uint32       `protobuf:"varint,10,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`
	ReceivedTimestamp int64        `protobuf:"varint,11,opt,name=received_timestamp,json=receivedTimestamp,proto3" json:"received_timestamp,omitempty"`
}

func (x *Probe) Reset() {
	*x = Probe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Probe) ProtoMessage() {}

func (x *Probe) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Probe.ProtoReflect.Descriptor instead.
func (*Probe) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{4}
}

func (x *Probe) GetSpooferIp() uint32 {
	if x != nil {
		return x.SpooferIp
	}
	return 0
}

func (x *Probe) GetProbeId() uint32 {
	if x != nil {
		return x.ProbeId
	}
	return 0
}

func (x *Probe) GetSrc() uint32 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *Probe) GetDst() uint32 {
	if x != nil {
		return x.Dst
	}
	return 0
}

func (x *Probe) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Probe) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *Probe) GetRR() *RecordRoute {
	if x != nil {
		return x.RR
	}
	return nil
}

func (x *Probe) GetTs() *TimeStamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Probe) GetSenderIp() uint32 {
	if x != nil {
		return x.SenderIp
	}
	return 0
}

func (x *Probe) GetReceivedTimestamp() int64 {
	if x != nil {
		return x.ReceivedTimestamp
	}
	return 0
}

type RecordRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hops []uint32 `protobuf:"varint,1,rep,packed,name=hops,proto3" json:"hops,omitempty"`
}

func (x *RecordRoute) Reset() {
	*x = RecordRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRoute) ProtoMessage() {}

func (x *RecordRoute) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRoute.ProtoReflect.Descriptor instead.
func (*RecordRoute) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{5}
}

func (x *RecordRoute) GetHops() []uint32 {
	if x != nil {
		return x.Hops
	}
	return nil
}

type TimeStamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   TSType   `protobuf:"varint,1,opt,name=type,proto3,enum=datamodel.TSType" json:"type,omitempty"`
	Stamps []*Stamp `protobuf:"bytes,2,rep,name=stamps,proto3" json:"stamps,omitempty"`
}

func (x *TimeStamp) Reset() {
	*x = TimeStamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStamp) ProtoMessage() {}

func (x *TimeStamp) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStamp.ProtoReflect.Descriptor instead.
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{6}
}

func (x *TimeStamp) GetType() TSType {
	if x != nil {
		return x.Type
	}
	return TSType_TSOnly
}

func (x *TimeStamp) GetStamps() []*Stamp {
	if x != nil {
		return x.Stamps
	}
	return nil
}

type Stamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time uint32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Ip   uint32 `protobuf:"varint,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *Stamp) Reset() {
	*x = Stamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stamp) ProtoMessage() {}

func (x *Stamp) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stamp.ProtoReflect.Descriptor instead.
func (*Stamp) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{7}
}

func (x *Stamp) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Stamp) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

type NotifyRecSpoofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *NotifyRecSpoofResponse) Reset() {
	*x = NotifyRecSpoofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRecSpoofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRecSpoofResponse) ProtoMessage() {}

func (x *NotifyRecSpoofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRecSpoofResponse.ProtoReflect.Descriptor instead.
func (*NotifyRecSpoofResponse) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyRecSpoofResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReceiveSpoofedProbesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReceiveSpoofedProbesResponse) Reset() {
	*x = ReceiveSpoofedProbesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recspoof_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveSpoofedProbesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveSpoofedProbesResponse) ProtoMessage() {}

func (x *ReceiveSpoofedProbesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recspoof_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveSpoofedProbesResponse.ProtoReflect.Descriptor instead.
func (*ReceiveSpoofedProbesResponse) Descriptor() ([]byte, []int) {
	return file_recspoof_proto_rawDescGZIP(), []int{9}
}

var File_recspoof_proto protoreflect.FileDescriptor

var file_recspoof_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x63, 0x73, 0x70, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x34, 0x0a, 0x08, 0x52,
	0x65, 0x63, 0x53, 0x70, 0x6f, 0x6f, 0x66, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x70, 0x6f, 0x6f, 0x66,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x53, 0x70, 0x6f, 0x6f, 0x66, 0x52, 0x06, 0x73, 0x70, 0x6f, 0x6f, 0x66,
	0x73, 0x22, 0x4b, 0x0a, 0x05, 0x53, 0x70, 0x6f, 0x6f, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22, 0x39,
	0x0a, 0x0d, 0x53, 0x70, 0x6f, 0x6f, 0x66, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x12,
	0x28, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x70, 0x6f,
	0x6f, 0x66, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xa9, 0x02, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x70, 0x6f, 0x6f, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x73, 0x70, 0x6f, 0x6f, 0x66, 0x65, 0x72, 0x49, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65,
	0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x71,
	0x4e, 0x75, 0x6d, 0x12, 0x27, 0x0a, 0x03, 0x72, 0x5f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x02, 0x72, 0x52, 0x12, 0x24, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02,
	0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x70, 0x12,
	0x2d, 0x0a, 0x12, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x25,
	0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x04, 0x68, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x10, 0x01, 0x52,
	0x04, 0x68, 0x6f, 0x70, 0x73, 0x22, 0x5c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x53, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x73, 0x22, 0x2b, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x70,
	0x22, 0x2e, 0x0a, 0x16, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x53, 0x70, 0x6f,
	0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x53, 0x70, 0x6f, 0x6f, 0x66,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2a, 0x32, 0x0a, 0x06, 0x54, 0x53, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x53,
	0x4f, 0x6e, 0x6c, 0x79, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x53, 0x41, 0x6e, 0x64, 0x41,
	0x64, 0x64, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x53, 0x50, 0x72, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x10, 0x03, 0x42, 0x0b, 0x5a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recspoof_proto_rawDescOnce sync.Once
	file_recspoof_proto_rawDescData = file_recspoof_proto_rawDesc
)

func file_recspoof_proto_rawDescGZIP() []byte {
	file_recspoof_proto_rawDescOnce.Do(func() {
		file_recspoof_proto_rawDescData = protoimpl.X.CompressGZIP(file_recspoof_proto_rawDescData)
	})
	return file_recspoof_proto_rawDescData
}

var file_recspoof_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recspoof_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_recspoof_proto_goTypes = []interface{}{
	(TSType)(0),                          // 0: datamodel.TSType
	(*RecSpoof)(nil),                     // 1: datamodel.RecSpoof
	(*Spoof)(nil),                        // 2: datamodel.Spoof
	(*SpoofedProbes)(nil),                // 3: datamodel.SpoofedProbes
	(*SpoofedProbesResponse)(nil),        // 4: datamodel.SpoofedProbesResponse
	(*Probe)(nil),                        // 5: datamodel.Probe
	(*RecordRoute)(nil),                  // 6: datamodel.RecordRoute
	(*TimeStamp)(nil),                    // 7: datamodel.TimeStamp
	(*Stamp)(nil),                        // 8: datamodel.Stamp
	(*NotifyRecSpoofResponse)(nil),       // 9: datamodel.NotifyRecSpoofResponse
	(*ReceiveSpoofedProbesResponse)(nil), // 10: datamodel.ReceiveSpoofedProbesResponse
}
var file_recspoof_proto_depIdxs = []int32{
	2, // 0: datamodel.RecSpoof.spoofs:type_name -> datamodel.Spoof
	5, // 1: datamodel.SpoofedProbes.probes:type_name -> datamodel.Probe
	6, // 2: datamodel.Probe.r_r:type_name -> datamodel.RecordRoute
	7, // 3: datamodel.Probe.ts:type_name -> datamodel.TimeStamp
	0, // 4: datamodel.TimeStamp.type:type_name -> datamodel.TSType
	8, // 5: datamodel.TimeStamp.stamps:type_name -> datamodel.Stamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_recspoof_proto_init() }
func file_recspoof_proto_init() {
	if File_recspoof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recspoof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecSpoof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spoof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpoofedProbes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpoofedProbesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Probe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeStamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyRecSpoofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recspoof_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveSpoofedProbesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recspoof_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recspoof_proto_goTypes,
		DependencyIndexes: file_recspoof_proto_depIdxs,
		EnumInfos:         file_recspoof_proto_enumTypes,
		MessageInfos:      file_recspoof_proto_msgTypes,
	}.Build()
	File_recspoof_proto = out.File
	file_recspoof_proto_rawDesc = nil
	file_recspoof_proto_goTypes = nil
	file_recspoof_proto_depIdxs = nil
}
