// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/NEU-SNS/ReverseTraceroute/datamodel/vantagepoint.proto

package datamodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VantagePoint struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   uint32   `protobuf:"varint,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Sshable              bool     `protobuf:"varint,3,opt,name=sshable,proto3" json:"sshable,omitempty"`
	Timestamp            bool     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RecordRoute          bool     `protobuf:"varint,5,opt,name=record_route,json=recordRoute,proto3" json:"record_route,omitempty"`
	LastUpdated          int64    `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	CanSpoof             bool     `protobuf:"varint,7,opt,name=can_spoof,json=canSpoof,proto3" json:"can_spoof,omitempty"`
	Controller           uint32   `protobuf:"varint,8,opt,name=controller,proto3" json:"controller,omitempty"`
	ReceiveSpoof         bool     `protobuf:"varint,9,opt,name=receive_spoof,json=receiveSpoof,proto3" json:"receive_spoof,omitempty"`
	Site                 string   `protobuf:"bytes,10,opt,name=site,proto3" json:"site,omitempty"`
	SpoofChecked         int64    `protobuf:"varint,11,opt,name=spoof_checked,json=spoofChecked,proto3" json:"spoof_checked,omitempty"`
	Port                 uint32   `protobuf:"varint,12,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VantagePoint) Reset()         { *m = VantagePoint{} }
func (m *VantagePoint) String() string { return proto.CompactTextString(m) }
func (*VantagePoint) ProtoMessage()    {}
func (*VantagePoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c66ff5e3bfa6eb8, []int{0}
}

func (m *VantagePoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VantagePoint.Unmarshal(m, b)
}
func (m *VantagePoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VantagePoint.Marshal(b, m, deterministic)
}
func (m *VantagePoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VantagePoint.Merge(m, src)
}
func (m *VantagePoint) XXX_Size() int {
	return xxx_messageInfo_VantagePoint.Size(m)
}
func (m *VantagePoint) XXX_DiscardUnknown() {
	xxx_messageInfo_VantagePoint.DiscardUnknown(m)
}

var xxx_messageInfo_VantagePoint proto.InternalMessageInfo

func (m *VantagePoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *VantagePoint) GetIp() uint32 {
	if m != nil {
		return m.Ip
	}
	return 0
}

func (m *VantagePoint) GetSshable() bool {
	if m != nil {
		return m.Sshable
	}
	return false
}

func (m *VantagePoint) GetTimestamp() bool {
	if m != nil {
		return m.Timestamp
	}
	return false
}

func (m *VantagePoint) GetRecordRoute() bool {
	if m != nil {
		return m.RecordRoute
	}
	return false
}

func (m *VantagePoint) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *VantagePoint) GetCanSpoof() bool {
	if m != nil {
		return m.CanSpoof
	}
	return false
}

func (m *VantagePoint) GetController() uint32 {
	if m != nil {
		return m.Controller
	}
	return 0
}

func (m *VantagePoint) GetReceiveSpoof() bool {
	if m != nil {
		return m.ReceiveSpoof
	}
	return false
}

func (m *VantagePoint) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *VantagePoint) GetSpoofChecked() int64 {
	if m != nil {
		return m.SpoofChecked
	}
	return 0
}

func (m *VantagePoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type VPRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPRequest) Reset()         { *m = VPRequest{} }
func (m *VPRequest) String() string { return proto.CompactTextString(m) }
func (*VPRequest) ProtoMessage()    {}
func (*VPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c66ff5e3bfa6eb8, []int{1}
}

func (m *VPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPRequest.Unmarshal(m, b)
}
func (m *VPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPRequest.Marshal(b, m, deterministic)
}
func (m *VPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPRequest.Merge(m, src)
}
func (m *VPRequest) XXX_Size() int {
	return xxx_messageInfo_VPRequest.Size(m)
}
func (m *VPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VPRequest proto.InternalMessageInfo

type VPReturn struct {
	Vps                  []*VantagePoint `protobuf:"bytes,1,rep,name=vps,proto3" json:"vps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VPReturn) Reset()         { *m = VPReturn{} }
func (m *VPReturn) String() string { return proto.CompactTextString(m) }
func (*VPReturn) ProtoMessage()    {}
func (*VPReturn) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c66ff5e3bfa6eb8, []int{2}
}

func (m *VPReturn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPReturn.Unmarshal(m, b)
}
func (m *VPReturn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPReturn.Marshal(b, m, deterministic)
}
func (m *VPReturn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPReturn.Merge(m, src)
}
func (m *VPReturn) XXX_Size() int {
	return xxx_messageInfo_VPReturn.Size(m)
}
func (m *VPReturn) XXX_DiscardUnknown() {
	xxx_messageInfo_VPReturn.DiscardUnknown(m)
}

var xxx_messageInfo_VPReturn proto.InternalMessageInfo

func (m *VPReturn) GetVps() []*VantagePoint {
	if m != nil {
		return m.Vps
	}
	return nil
}

type RRSpooferRequest struct {
	Addr                 uint32   `protobuf:"varint,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Max                  uint32   `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RRSpooferRequest) Reset()         { *m = RRSpooferRequest{} }
func (m *RRSpooferRequest) String() string { return proto.CompactTextString(m) }
func (*RRSpooferRequest) ProtoMessage()    {}
func (*RRSpooferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c66ff5e3bfa6eb8, []int{3}
}

func (m *RRSpooferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RRSpooferRequest.Unmarshal(m, b)
}
func (m *RRSpooferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RRSpooferRequest.Marshal(b, m, deterministic)
}
func (m *RRSpooferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RRSpooferRequest.Merge(m, src)
}
func (m *RRSpooferRequest) XXX_Size() int {
	return xxx_messageInfo_RRSpooferRequest.Size(m)
}
func (m *RRSpooferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RRSpooferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RRSpooferRequest proto.InternalMessageInfo

func (m *RRSpooferRequest) GetAddr() uint32 {
	if m != nil {
		return m.Addr
	}
	return 0
}

func (m *RRSpooferRequest) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type RRSpooferResponse struct {
	Addr                 uint32          `protobuf:"varint,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Max                  uint32          `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Spoofers             []*VantagePoint `protobuf:"bytes,3,rep,name=spoofers,proto3" json:"spoofers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RRSpooferResponse) Reset()         { *m = RRSpooferResponse{} }
func (m *RRSpooferResponse) String() string { return proto.CompactTextString(m) }
func (*RRSpooferResponse) ProtoMessage()    {}
func (*RRSpooferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c66ff5e3bfa6eb8, []int{4}
}

func (m *RRSpooferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RRSpooferResponse.Unmarshal(m, b)
}
func (m *RRSpooferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RRSpooferResponse.Marshal(b, m, deterministic)
}
func (m *RRSpooferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RRSpooferResponse.Merge(m, src)
}
func (m *RRSpooferResponse) XXX_Size() int {
	return xxx_messageInfo_RRSpooferResponse.Size(m)
}
func (m *RRSpooferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RRSpooferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RRSpooferResponse proto.InternalMessageInfo

func (m *RRSpooferResponse) GetAddr() uint32 {
	if m != nil {
		return m.Addr
	}
	return 0
}

func (m *RRSpooferResponse) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *RRSpooferResponse) GetSpoofers() []*VantagePoint {
	if m != nil {
		return m.Spoofers
	}
	return nil
}

type TSSpooferRequest struct {
	Max                  uint32   `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TSSpooferRequest) Reset()         { *m = TSSpooferRequest{} }
func (m *TSSpooferRequest) String() string { return proto.CompactTextString(m) }
func (*TSSpooferRequest) ProtoMessage()    {}
func (*TSSpooferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c66ff5e3bfa6eb8, []int{5}
}

func (m *TSSpooferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TSSpooferRequest.Unmarshal(m, b)
}
func (m *TSSpooferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TSSpooferRequest.Marshal(b, m, deterministic)
}
func (m *TSSpooferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TSSpooferRequest.Merge(m, src)
}
func (m *TSSpooferRequest) XXX_Size() int {
	return xxx_messageInfo_TSSpooferRequest.Size(m)
}
func (m *TSSpooferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TSSpooferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TSSpooferRequest proto.InternalMessageInfo

func (m *TSSpooferRequest) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type TSSpooferResponse struct {
	Max                  uint32          `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Spoofers             []*VantagePoint `protobuf:"bytes,2,rep,name=spoofers,proto3" json:"spoofers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TSSpooferResponse) Reset()         { *m = TSSpooferResponse{} }
func (m *TSSpooferResponse) String() string { return proto.CompactTextString(m) }
func (*TSSpooferResponse) ProtoMessage()    {}
func (*TSSpooferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c66ff5e3bfa6eb8, []int{6}
}

func (m *TSSpooferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TSSpooferResponse.Unmarshal(m, b)
}
func (m *TSSpooferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TSSpooferResponse.Marshal(b, m, deterministic)
}
func (m *TSSpooferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TSSpooferResponse.Merge(m, src)
}
func (m *TSSpooferResponse) XXX_Size() int {
	return xxx_messageInfo_TSSpooferResponse.Size(m)
}
func (m *TSSpooferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TSSpooferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TSSpooferResponse proto.InternalMessageInfo

func (m *TSSpooferResponse) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *TSSpooferResponse) GetSpoofers() []*VantagePoint {
	if m != nil {
		return m.Spoofers
	}
	return nil
}

func init() {
	proto.RegisterType((*VantagePoint)(nil), "datamodel.VantagePoint")
	proto.RegisterType((*VPRequest)(nil), "datamodel.VPRequest")
	proto.RegisterType((*VPReturn)(nil), "datamodel.VPReturn")
	proto.RegisterType((*RRSpooferRequest)(nil), "datamodel.RRSpooferRequest")
	proto.RegisterType((*RRSpooferResponse)(nil), "datamodel.RRSpooferResponse")
	proto.RegisterType((*TSSpooferRequest)(nil), "datamodel.TSSpooferRequest")
	proto.RegisterType((*TSSpooferResponse)(nil), "datamodel.TSSpooferResponse")
}

func init() {
	proto.RegisterFile("github.com/NEU-SNS/ReverseTraceroute/datamodel/vantagepoint.proto", fileDescriptor_3c66ff5e3bfa6eb8)
}

var fileDescriptor_3c66ff5e3bfa6eb8 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x95, 0x64, 0x6c, 0xc9, 0x4b, 0x8a, 0x3a, 0x5f, 0xb0, 0x00, 0xa1, 0x10, 0x38, 0x84,
	0x03, 0xad, 0xc4, 0x84, 0xc4, 0x15, 0x10, 0xd7, 0x69, 0x72, 0xb7, 0x1d, 0x76, 0xa9, 0x5c, 0xe7,
	0xb1, 0x46, 0x24, 0xb6, 0xb1, 0x9d, 0x8a, 0xff, 0x98, 0x7f, 0x03, 0xd9, 0x09, 0x6d, 0x01, 0x09,
	0xed, 0xf6, 0xde, 0xe7, 0xef, 0x7d, 0xfe, 0xc9, 0xcf, 0xf0, 0xf1, 0xbe, 0x75, 0xdb, 0x61, 0xb3,
	0x10, 0xaa, 0x5f, 0x5e, 0x7e, 0xb9, 0x79, 0xbb, 0xba, 0x5c, 0x2d, 0x19, 0xee, 0xd0, 0x58, 0xbc,
	0x36, 0x5c, 0xa0, 0x51, 0x83, 0xc3, 0x65, 0xc3, 0x1d, 0xef, 0x55, 0x83, 0xdd, 0x72, 0xc7, 0xa5,
	0xe3, 0xf7, 0xa8, 0x55, 0x2b, 0xdd, 0x42, 0x1b, 0xe5, 0x14, 0xc9, 0xf6, 0xa7, 0xd5, 0xcf, 0x18,
	0x8a, 0xdb, 0xd1, 0x71, 0xe5, 0x1d, 0xe4, 0x29, 0xa4, 0x5b, 0x65, 0x9d, 0xe4, 0x3d, 0xd2, 0xa8,
	0x8c, 0xea, 0x8c, 0xed, 0x7b, 0xf2, 0x18, 0xe2, 0x56, 0xd3, 0xb8, 0x8c, 0xea, 0x19, 0x8b, 0x5b,
	0x4d, 0x28, 0x9c, 0x59, 0xbb, 0xe5, 0x9b, 0x0e, 0x69, 0x52, 0x46, 0x75, 0xca, 0x7e, 0xb7, 0xe4,
	0x39, 0x64, 0xae, 0xed, 0xd1, 0x3a, 0xde, 0x6b, 0x7a, 0x12, 0xce, 0x0e, 0x02, 0x79, 0x09, 0x85,
	0x41, 0xa1, 0x4c, 0xb3, 0x0e, 0xb0, 0xf4, 0x51, 0x30, 0xe4, 0xa3, 0xc6, 0xbc, 0xe4, 0x2d, 0x1d,
	0xb7, 0x6e, 0x3d, 0xe8, 0x86, 0x3b, 0x6c, 0xe8, 0x69, 0x19, 0xd5, 0x09, 0xcb, 0xbd, 0x76, 0x33,
	0x4a, 0xe4, 0x19, 0x64, 0x82, 0xcb, 0xb5, 0xd5, 0x4a, 0x7d, 0xa5, 0x67, 0x21, 0x22, 0x15, 0x5c,
	0xae, 0x7c, 0x4f, 0x5e, 0x00, 0x08, 0x25, 0x9d, 0x51, 0x5d, 0x87, 0x86, 0xa6, 0x01, 0xf9, 0x48,
	0x21, 0xaf, 0x60, 0x66, 0x50, 0x60, 0xbb, 0xc3, 0x29, 0x20, 0x0b, 0x01, 0xc5, 0x24, 0x8e, 0x21,
	0x04, 0x4e, 0x6c, 0xeb, 0x90, 0x42, 0x78, 0x87, 0x50, 0xfb, 0xc1, 0x30, 0xb0, 0x16, 0x5b, 0x14,
	0xdf, 0xb0, 0xa1, 0x79, 0x20, 0x2b, 0x82, 0xf8, 0x79, 0xd4, 0xfc, 0xa0, 0x56, 0xc6, 0xd1, 0x22,
	0xdc, 0x1b, 0xea, 0x2a, 0x87, 0xec, 0xf6, 0x8a, 0xe1, 0xf7, 0x01, 0xad, 0xab, 0xde, 0x43, 0xea,
	0x1b, 0x37, 0x18, 0x49, 0xde, 0x40, 0xb2, 0xd3, 0x96, 0x46, 0x65, 0x52, 0xe7, 0xef, 0x9e, 0x2c,
	0xf6, 0xbb, 0x59, 0x1c, 0xef, 0x85, 0x79, 0x4f, 0xf5, 0x01, 0xe6, 0x8c, 0x05, 0x36, 0x34, 0x53,
	0x94, 0xbf, 0x8b, 0x37, 0x8d, 0x09, 0xcb, 0x9a, 0xb1, 0x50, 0x93, 0x39, 0x24, 0x3d, 0xff, 0x31,
	0x6d, 0xca, 0x97, 0x95, 0x84, 0xf3, 0xa3, 0x49, 0xab, 0x95, 0xb4, 0xf8, 0xb0, 0x51, 0x72, 0x01,
	0xa9, 0x1d, 0x07, 0x2d, 0x4d, 0xfe, 0x0f, 0xb9, 0x37, 0x56, 0xaf, 0x61, 0x7e, 0xbd, 0xfa, 0x8b,
	0x74, 0x8a, 0x8e, 0x0e, 0x54, 0x77, 0x70, 0x7e, 0xe4, 0x9a, 0xa8, 0xfe, 0xb1, 0xfd, 0x41, 0x10,
	0x3f, 0x90, 0xe0, 0x53, 0x7e, 0x77, 0xf8, 0xe6, 0x9b, 0xd3, 0xf0, 0xf1, 0x2f, 0x7e, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x27, 0x11, 0x65, 0xfd, 0x3d, 0x03, 0x00, 0x00,
}
